clean/clean/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from profiles import views
from tastypie.api import Api
from django.views.generic import TemplateView
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import activate
from apis.profile_response import *

v1_api = Api(api_name='v1')
v1_api.register(PrivateUserResource())
v1_api.register(PrivateProfileResource())
v1_api.register(PrivateCourseResource())
v1_api.register(PublicUserResource())
v1_api.register(PublicProfileResource())
v1_api.register(PublicCourseResource())
v1_api.register(CourseTypeResource())
v1_api.register(CourseSearchResource())

urlpatterns = patterns('',)

urlpatterns += i18n_patterns(
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include(v1_api.urls)),
    url(r'^profile/', include('profiles.urls', namespace='profile')),
    url(r'^search/', TemplateView.as_view(template_name='search.html'), name='search'),
    url(r'^langs/$', views.change_language, name='lang'),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),

)

clean/profiles/urls.py
from django.conf.urls import patterns, url
from profiles import views
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

urlpatterns = patterns("",
    url(r'^$', TemplateView.as_view(template_name='create_profile.html'), name='create_profile'),
    url(r'^edit_profile/$', login_required(TemplateView.as_view(template_name='edit_profile.html')), name='edit_profile'),
    url(r'^edit_course/$', login_required(views.CourseEdit.as_view()), name='edit_course'),
    url(r'^create_course/$', login_required(TemplateView.as_view(template_name='create_course.html')), name='create_course'),
    url(r'^login/$', views.login_user, name='login'),
    url(r'^logout/$', views.logout_user, name='logout'),
)

clean/profiles/models.py
from django.db import models
from django.contrib.auth.models import User

class CourseType(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __unicode__(self):
        return self.name

class Profile(models.Model):
    user = models.ForeignKey(User)
    country = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    zip_code = models.CharField(max_length=10)
    user_desciption = models.TextField()

    def __unicode__(self):
        return self.user.username

class Course(models.Model):
    course_name = models.CharField(max_length=100)
    course_type = models.ForeignKey(CourseType)
    course_desciption = models.TextField()
    owner = models.ForeignKey(Profile)
    price = models.IntegerField()

    def __unicode__(self):
        return self.course_name

# Create your models here.

clean/profiles/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, logout, login
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView
from django.utils import translation
from django.core.urlresolvers import reverse

def login_user(request):
    logout(request)
    if request.POST:
        password = request.POST['password']
        username = request.POST['username']

        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def logout_user(request):
    logout(request)
    return HttpResponseRedirect('/')

def change_language(request):
    if request.GET:
        lang = request.GET.get('language', '')
        if lang:
            translation.activate(lang)
            print translation.get_language()
            request.LANGUAGE_CODE = translation.get_language()
            return HttpResponseRedirect(reverse('home'))
            
    
    return HttpResponseRedirect('/')


class CourseEdit(TemplateView):
    template_name = 'edit_course.html'

    def get_context_data(self, **kwargs):
        print "aaaaaaaaaa", self.args
        context = super(CourseEdit, self).get_context_data(**kwargs)
        if self.request.method == 'GET':
            context['resource'] = self.request.GET['resource']
        return context
        

# Create your views here.

clean/templates/base.html
{% load staticfiles %}
{% load i18n %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'js/underscore-min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/backbone-min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/backbone-tastypie.js' %}"></script>
</head>
<body>
    <script type="text/javascript">
        function changeLang() {
            var lang = $('#languages').val();
            alert(lang);
            window.location.href = "{% url 'lang' %}?language="+lang;
            // $.ajax({
            //     type: 'GET',
            //     url: "{% url 'lang' %}",
            //     data:  {"language": lang},
            // });
        }

    </script>
    {% if request.user.is_active %} 
        <div> in {{request.user.username}} </div>
        <div> id {{request.user.id}} </div>
        <a href="{% url 'profile:logout' %}">{% trans "Logout" %}</a>
        <a href="{% url 'profile:create_course' %}">{% trans "Create course" %}</a>
        <a href="{% url 'profile:edit_profile' %}">{% trans "Edit Profile" %}</a>
    {% else %}
        <form action="{% url 'profile:login' %}" method="POST">
            {% csrf_token %}
            <label>username: </label>
            <input name="username" type="text" id="username" value="">
            <label>password: </label>
            <input name="password" type="password" id="password" value="">
            <input type="submit" value="Go">
        </form>
        <a href="{% url 'profile:create_profile' %}">{% trans "Registrate" %}</a>
    {% endif %}
    <a href="{% url 'search' %}">{% trans "Search" %}</a>
    <div>
        <label>{% trans "Language" %}</label>
        <select onchange="changeLang()" id="languages">
            <option value="">{{request.LANGUAGE_CODE}}</option>
            <option value="en">EN</option>
            <option value="ua">UA</option>
            <option value="ru">RU</option>
        </select><br/>
    </div>
    {% block content %}{% endblock %}
</body>
</html>

clean/templates/create_course.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Cource create" %}{% endblock %}

{% block content %}
<script type="text/template" id="option_template">
    <option value="<%= id %>"><%= name %></option>
</script>
<script type="text/javascript">
$(function(){

    CourseTypeModel = Backbone.Model.extend({
        urlRoot: '/api/v1/course_type/'
    });

    CourseTypeCollection = Backbone.Collection.extend({
        model: CourseTypeModel,
        url: '/api/v1/course_type/'
    });

    CourseTypeView = Backbone.View.extend({
        el: "#course_type",
        initialize: function() {
            _.bindAll(this, 'render');
            this.collection = new CourseTypeCollection();
            var that = this;
            this.collection.fetch({
                success: function(course_types){
                    that.render(course_types.toJSON())
                }
            });
        },
        template: _.template('<option value="<%= id %>"><%= name %></option>'),
        render: function(course_types){
            var that = this;
            course_types.forEach(function(course_type){
                that.$el.append(that.template(course_type));
            });
        }
    });

    CourseModel = Backbone.Model.extend({
        urlRoot: '/api/v1/private_course/',
        defaults: {
            'course_type': '',
            'course_desciption': '',
            'course_name': '',
            'price': ''
        }
    });

    CourseView = Backbone.View.extend({
        el: '#courseForm',
        events: {
            'click #create': 'submitCreate'
        },
        initialize: function() {
            _.bindAll(this, 'submitCreate');
            this.model = new CourseModel();
        },
        submitCreate: function() {
            var unindexed_array = this.$el.serializeArray();
            var data = {};
            alert(JSON.stringify(unindexed_array))
            unindexed_array.forEach(function(n){
                data[n.name] = n.value;
            });             
            this.model.set(data);
            this.model.save();
        },
    });

    return new CourseTypeView(), new CourseView();
})
</script>
<h5>Vaaavaaa</h5>
<form id="courseForm">
    {% csrf_token %}
    <label>{% trans "course type: "%}</label>
    <select name="course_type" id="course_type">
        
    </select><br/>
    <label>{% trans "course desciption: "%}</label>
    <input name="course_desciption" type="text" id="course_desciption" value=""><br/>
    <label>{% trans "course name: "%}</label>
    <input name="course_name" type="text" id="course_name" value=""><br/>
    <label>{% trans "course price: "%}</label>
    <input name="price" type="text" id="price" value=""><br/>
    <input type="submit" id="create" value={% trans "Go" %}>
</form>
{% endblock %}

clean/templates/create_profile.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}

{% block content %}
<script type="text/javascript">
$(function(){


    ProfileModel = Backbone.Model.extend({
        urlRoot: '/api/v1/profile/',
        defaults: {
            'username' : '',
            'password' : '',
            'email' : '',
            'country' : '',
            'city' : '',
            'zip_code' : '',
            'user_desciption' : ''
        }
    });

    ProfileView = Backbone.View.extend({
        el: '#profileForm',
        events: {
            'click #create': 'submitCreate'
        },
        initialize: function() {
            _.bindAll(this, 'submitCreate');
            this.model = new ProfileModel();
        },
        submitCreate: function() {
            var form = this.$el;
            var self = this;
            var unindexed_array = form.serializeArray();
            var data = {};

            unindexed_array.forEach(function(n){
                data[n.name] = n.value;
            });             
            self.model.set(data);
            self.model.save();
        },
    });

    return new ProfileView()
})
</script>
<h5>Vaaavaaa</h5>
<form id="profileForm">
    {% csrf_token %}
    <label>username: </label>
    <input name="username" type="text" id="username" value=""><br/>
    <label>password: </label>
    <input name="password" type="password" id="password" value=""><br/>
    <label>email: </label>
    <input name="email" type="text" id="email" value=""><br/>
    <label>country: </label>
    <input name="country" type="text" id="country" value=""><br/>
    <label>city: </label>
    <input name="city" type="text" id="city" value=""><br/>
    <label>zip code: </label>
    <input name="zip_code" type="text" id="zip_code" value=""><br/>
    <label>about your self: </label>
    <input name="user_desciption" type="text" id="user_desciption" value=""><br/>
    <input type="submit" id="create" value="Go">
</form>
{% endblock %}

clean/templates/edit_course.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Edit course"%}{% endblock %}

{% block content %}
<script type="text/template" id="templateForm">
    {% csrf_token %}
    <label>{% trans "Course type: "%}</label>
    <input readonly name="course_type" type="text" id="course_type" value="<%= course_type.name %>"><br/>
    <label>{% trans "Course name: "%}</label>
    <input name="course_name" type="text" id="course_name" value="<%= course_name %>"><br/>
    <label>{% trans "Course desciption: "%}</label>
    <input name="course_desciption" type="text" id="course_desciption" value="<%= course_desciption %>"><br/>
    <label>{% trans "price: "%}</label>
    <input name="price" type="text" id="price" value="<%= price %>"><br/>
    <input type="button" id="update" value={% trans "Change"%}>
</script>
<script type="text/javascript">
$(function(){
    
    CourseModel = Backbone.Model.extend({
        urlRoot: '/api/v1/private_course/',
        defaults: {
            'course_desciption': '',
            'course_name': '',
            'price': ''
        }
    });

    CourseView = Backbone.View.extend({
        el: '#profileForm',
        events: {
            'click #update': 'submitUpdate'
        },
        initialize: function(){
            _.bindAll(this, 'render', 'submitUpdate');
            this.model = new CourseModel({resource_uri: '{{resource}}'});
            var that = this;
            this.model.fetch( {
                success: function(course){
                    that.render( course.toJSON() )
                }
            });
        },
        submitUpdate: function() {
            var form = this.$el;
            var unindexed_array = form.serializeArray();
            var data = {};

            unindexed_array.forEach(function(n){
                if ( n.name != 'course_type') {
                    data[n.name] = n.value;
                };
            });             
            alert(JSON.stringify(data));
            this.model.set( data );
            this.model.save();
        },
        render: function(course) {
            alert( JSON.stringify(course) );
            var template = _.template( $("#templateForm").html() );
            this.$el.html( template(course) );
        },
    });

    return new CourseView();
})
</script>
<h5>Vaaavaaa</h5>
<form id="profileForm"></form>


{% endblock %}

clean/templates/edit_profile.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}

{% block content %}
<script type="text/template" id="templateForm">
    {% csrf_token %}
    <label>country: </label>
    <input name="country" type="text" id="country" value="<%= country %>"><br/>
    <label>city: </label>
    <input name="city" type="text" id="city" value="<%= city %>"><br/>
    <label>zip code: </label>
    <input name="zip_code" type="text" id="zip_code" value="<%= zip_code %>"><br/>
    <label>about your self: </label>
    <input name="user_desciption" type="text" id="user_desciption" value="<%= user_desciption %>"><br/>
    <input type="button" id="update" value="Change">
</script>
<script type="text/javascript">
$(function(){
    
    CourseModel = Backbone.Model.extend({
        urlRoot: '/api/v1/private_course/',
        defaults: {
            'course_type': '',
            'course_desciption': '',
            'course_name': '',
            'price': ''
        }
    });

    CourseCollection = Backbone.Collection.extend({
        model: CourseModel,
        url: '/api/v1/private_course/',
    });

    CourseView = Backbone.View.extend({
        el: '#course_list',
        initialize: function(){
            _.bindAll(this, 'render');
            this.collection = new CourseCollection();
            var that = this;
            this.collection.fetch( {
                success: function(list){
                    alert(JSON.stringify(list));
                    that.render(list.toJSON())
                }
            });
        },
        template: _.template("<a href='{% url 'profile:edit_course' %}?resource=<%= resource_uri %>'><%= course_name %></a></br>"),
        render: function(list){
            var that = this;
            list.forEach(function(course){
                that.$el.append(that.template(course));
            });
        },
    });

    ProfileModel = Backbone.Model.extend({
        urlRoot: '/api/v1/private_profile/',
        defaults: {
            'country' : '',
            'city' : '',
            'zip_code' : '',
            'user_desciption' : ''
        }
    });

    ProfileView = Backbone.View.extend({
        el: '#profileForm',
        events: {
            'click #update': 'submitUpdate'
        },
        initialize: function() {
            _.bindAll(this,'render', 'submitUpdate');
            this.model = new ProfileModel();
            var that = this;
            this.model.fetch({
                success: function(profile){
                    that.render(profile.toJSON());
                }
            })
        },        
        submitUpdate: function() {
            var form = this.$el;
            var unindexed_array = form.serializeArray();
            var data = {};

            alert(JSON.stringify(unindexed_array));
            unindexed_array.forEach(function(n){
                data[n.name] = n.value;
            });             
            this.model.set( data );
            this.model.save();
        },
        // template _.template($('#templateForm')),
        render: function(n) {
            var template = _.template( $("#templateForm").html());
            this.$el.html( template(n) );
        },
    });


    return new ProfileView(), new CourseView();
})
</script>
<h5>Vaaavaaa</h5>
<form id="profileForm"></form>

<div id="course_list"></div>

{% endblock %}

clean/templates/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}

{% block content %}
<script type="text/javascript">
$(function(){
    RegistryUserModel = Backbone.Model.extend({
        
        initialize: function() {
        },

        urlRoot: function() {
            return '/api/v1/private_profile/'; 
        },

    });

    ProfileModel = Backbone.Model.extend({
        
        initialize: function() {
        },

        urlRoot: function() {
            return '/api/v1/profile';
        },

    });

    Profiles = Backbone.Collection.extend({
        
        model: ProfileModel,

        url : '/api/v1/profile/',
    });

    var profile = new RegistryUserModel({id: {{request.user.id}}});

    profile.fetch({
        success: function(profile) {
            var u = profile.toJSON();
            // alert(JSON.stringify(u));
        }
    });
    // alert(profile.toJSON());



    ProfileView = Backbone.View.extend({
        
        el: '#booka',
        tagName: 'div',

        initialize: function() {
            _.bindAll(this, 'render');
            this.collection = new Profiles();
            var that = this;
            this.collection.fetch({
                success: function(profiles) {
                    that.render(profiles.toJSON());
                }
            });
        },

        template: _.template("<div> country: <%= country %>, ionfo: <%= user_desciption %>, city: <%= city  %> </div>"),

        render: function(profiles) {
            // alert(JSON.stringify(n));
            var that = this;
            profiles.forEach(function(profile){
                that.$el.append(that.template(profile));
            });
            // this.$el.html(this.template(n));
        }

    });

    return new ProfileView()

})
</script>
<h5>BooBaa</h5>
<div id="booka"></div>

{% endblock %}

clean/templates/search.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Search"%}{% endblock %}

{% block content %}
<script type="text/template" id="templateDiv">
    <% _.forEach(courses, function(course){ %>
        <div>
            {% trans "Subject: "%}<%= course.course_name %> <br/>
            {% trans "Courses: "%}<%= course.course_type.name %> <br/>
            {% trans "City: "%}<%= course.owner.city %> <br/>
            {% trans "Price: "%}<%= course.price %> <br/>
            {% trans "Discribe: "%}<%= course.course_desciption %> <br/>
        </div>
    <% }); %>
</script>
<script type="text/template" id="templateEmptyDiv">
    <div> No results </div>
</script>
<script type="text/javascript">
$(function(){
    CourseTypeModel = Backbone.Model.extend({
        urlRoot: '/api/v1/course_type/',
    });

    CourseTypeCollection = Backbone.Collection.extend({
        model: CourseTypeModel,
        url: '/api/v1/course_type/'
    });

    CourseTypeView = Backbone.View.extend({
        el: "#course_type",
        initialize: function() {
            _.bindAll(this, 'render');
            this.collection = new CourseTypeCollection();
            var that = this;
            this.collection.fetch({
                success: function(course_types){
                    that.render(course_types.toJSON())
                }
            });
        },
        template: _.template('<option value="<%= id %>"><%= name %></option>'),
        render: function(course_types){
            var that = this;
            course_types.forEach(function(course_type){
                that.$el.append(that.template(course_type));
            });
        }
    });

    SearchCourseModel = Backbone.Model.extend({
        urlRoot: '/api/v1/courses/search/'
    });

    SearchCourseCollection = Backbone.Collection.extend({
        
        model: SearchCourseModel,

        url : '/api/v1/courses/search/',
    });

    SearchView = Backbone.View.extend({
        el: '#searchForm',
        events: {
            'click #search': 'searchData',
            'change #course_type': 'searchData',
            'change #low_price': 'searchData',
            'change #up_price': 'searchData',
            'change input#city': 'searchData'
        },
        initialize: function(){
            _.bindAll(this, 'searchData', 'render');
        },
        searchData: function(){
            var that = this;
            var unindexed_array = this.$el.serializeArray();
            var data = {};

            unindexed_array.forEach(function(n){
                data[n.name] = n.value;
            });
            alert(JSON.stringify(data));
            $.ajax({
                type: 'GET',
                url: '/api/v1/courses/search/',
                data: data,
                success: function(data){
                    var parsed = $.parseJSON($.parseJSON(data));

                    console.log(parsed);
                    alert(typeof parsed);
                    that.render(parsed);     
                },
            });
            // var collection = new SearchCourseModel(data);
            // collection.fetch({
            //     success: function(courses){
            //         // that.render(courses.toJSON())
            //     }
            // });
        },
        render: function(courses){
            if ( courses.courses.length > 0 ) {
                var template = _.template( $("#templateDiv").html() );
                alert(JSON.stringify(courses));
                $('#results').html( template(courses) );
                // courses.forEach(function(course){
                // });
            } else {
                var template = _.template( $("#templateEmptyDiv").html() );
                $('#results').html( template );
            }
        }
    });

    return new CourseTypeView(), new SearchView();

})
</script>
<h5>BooBaa</h5>
<div id="booka"></div>
<form id="searchForm">
    <label>{% trans "Course type: "%}</label>
    <select name="course_type" id="course_type">
        <option value="">All</option>
    </select><br/>
    <label>{% trans "Course price: "%}</label><br/>
    <label>{% trans "from: "%}</label>
    <input name="low_price" type="text" id="low_price" value="0">
    <label> - {% trans "to: "%}</label>
    <input name="up_price" type="text" id="up_price" value="0"><br/>
    <label>{% trans "City: "%}</label>
    <input name="city" type="text" id="city" value=""><br/>
    <input type="button" id="search" value={% trans "Search"%}>
</form>
<div id="results"></div>
{% endblock %}